services:
  - type: web
    name: coltec-bet-api
    
    # A linha 'runtime' ou 'env' foi REMOVIDA.
    # O Render vai detectar o .NET por causa da rootDir abaixo,
    # onde ele encontrará o arquivo .csproj.
    rootDir: ColtecBet.Api
    
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/ColtecBet.Api.dll"
    healthCheckPath: /swagger/index.html
    
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: coltec-bet-db 
          property: connectionString

      # Adicione suas outras variáveis de ambiente aqui
      - key: Jwt__Key
        value: Coltecbetapichava123
      - key: Jwt__Issuer
        value: ColtecBet.Api
      - key: Jwt__Audience
        value: ColtecBet.Frontend