services:
  - type: web
    name: coltec-bet-api
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: coltec-bet-db 
          property: connectionString
      
      - key: Jwt__Key
        value: Coltecbetapichava123
      - key: Jwt__Issuer
        value: ColtecBet.Api
      - key: Jwt__Audience
        value: ColtecBet.Frontend
