services:
  - type: web
    name: coltec-bet-api
    
    # --- CORREÇÃO PRINCIPAL AQUI ---
    # A chave correta para especificar um build Docker é 'runtime'
    runtime: docker
    
    # --- AJUSTE IMPORTANTE ---
    # Define o contexto do build para a raiz do repositório,
    # onde o Dockerfile deve estar.
    rootDir: .
    dockerfilePath: ./Dockerfile

    plan: free
    
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: coltec-bet-db 
          property: connectionString
      
      - key: Jwt__Key
        value: Coltecbetapichava123
      - key: Jwt__Issuer
        value: ColtecBet.Api
      - key: Jwt__Audience
        value: ColtecBet.Frontend