services:
  - type: web
    name: coltec-bet-api
    
    # --- CORREÇÃO 1 AQUI ---
    # A chave correta para definir o ambiente é 'env'
    env: dotnet
    
    # O resto das nossas configurações
    rootDir: ColtecBet.Api
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/ColtecBet.Api.dll"
    healthCheckPath: /swagger/index.html
    
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: coltec-bet-db
          # --- CORREÇÃO 2 AQUI ---
          # A propriedade correta para a URL de conexão é 'connectionString'
          property: connectionString

      # Adicione suas outras variáveis de ambiente aqui
      - key: Jwt__Key
        value: Coltecbetapichava123
      - key: Jwt__Issuer
        value: ColtecBet.Api
      - key: Jwt__Audience
        value: ColtecBet.Frontend