services:
  - type: web
    name: coltec-bet-api
    env: docker    # 👈 ESSENCIAL: diz que esse serviço é baseado em Docker
    dockerfilePath: Dockerfile
    plan: free     # ou starter, dependendo do seu plano
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: coltec-bet-db 
          property: connectionString
      
      - key: Jwt__Key
        value: Coltecbetapichava123
      - key: Jwt__Issuer
        value: ColtecBet.Api
      - key: Jwt__Audience
        value: ColtecBet.Frontend
