// <auto-generated />
using System;
using ColtecBet.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColtecBet.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250806150208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ColtecBet.Api.Models.Aposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Escolha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPartida")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorRetorno")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("ColtecBet.Api.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Encerrada")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OddCasa")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OddEmpate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OddVisitante")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeCasa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeVisitante")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ColtecBet.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ColtecBet.Api.Models.Aposta", b =>
                {
                    b.HasOne("ColtecBet.Api.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId");

                    b.HasOne("ColtecBet.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
